### ISSUE TITLE
Rework error status codes

### ISSUE THREAD

**Issue by emaxedon** [edadma/energize#18]
If trying to POST with invalid fields, return a `400 Bad Request`. (Currently the server is returning a 500 Internal Server Error, which is incorrect).

If trying to POST a duplicate, return a `409 Conflict`.

Remember, 400 level errors are client errors. So if I don't send the server the valid data, I should always receive a 400 level error. If I had sent the valid data, and something actually went wrong because the server failed, then I should see a 500 level error (which means the server screwed up).

**Comment by edadma** [comment]
thanks for checking all this for me and sending the info - i was wondering exactly how to do all this error code stuff

**Comment by edadma** [comment]
> If trying to POST with invalid fields, return a 400 Bad Request. (Currently the server is returning a 500 Internal Server Error, which is incorrect).

Please show how to reproduce the above issue.  I tried posting with a that's not in the resource definition and it ignores it (which is also wrong).

**Comment by edadma** [comment]
a POST many not have fields that are not in the resource definition
