### ISSUE TITLE
Add support for "datetime" type

### ISSUE THREAD

**Issue by emaxedon** [edadma/energize#7]
Add support for "datetime" type following [ISO 8601 Date and Time Formats](https://www.w3.org/TR/NOTE-datetime) standard.

**Comment by edadma** [comment]
H2 treats DATETIME and TIMESTAMP as being equivalent; PostgreSQL doesn't have a DATETIME type, only TIMESTAMP so for PostgreSQL Energize will treat DATETIME to be equivalent to TIMESTAMP as well

**Comment by edadma** [comment]
Joda Time (java.time package) parses and formats ISO 8601 timestamps nicely

**Comment by edadma** [comment]
ISO 8601 timestamp support has been added for H2

**Comment by edadma** [comment]
The DATETIME and TIMESTAMP types are interchangeable for the reasons mentioned in the first comment and the fact that the Joda Time/java.time OffsetDateTime.parse method parses any ISO8601 date time variant correctly.
