### ISSUE TITLE
Add support for user authentication/management

### ISSUE THREAD

**Issue by emaxedon** [edadma/energize#9]
Implement a default user authentication and user management system.

Users would authenticate using basic auth with the `Authorization` header (something like `Authorization: Basic base64ofCredentials`). After successful log in they would receive an authentication token (that should only live for 24 hours by default) that they would pass along every subsequent request (something like `Authorization: Bearer someGeneratedToken`).

The default authentication actions should look like

Login
```
Request:
GET /auth/login HTTP/1.1
  Host: api.example.com
  Accept: application/json
  Authorization: Basic base64UserCrendetials

Response:
200 OK
{"token": "someGeneratedToken"}
```

Logout
```
GET /auth/logout HTTP/1.1
  Host: api.example.com
  Authorization: Bearer someGeneratedToken

Response:
200 OK
```

Logging out destroys the token from the database and removes their access.

Users should have `email`, `createdTime`, `updatedTime`, `state`, `groups`, and `password` as default fields.

Should they want to add fields to a user, they would add properties to the `users` resource which is created by default.

```
resource users
  firstName string optional
  lastName string optional
```

An `email` should be required for users, so that after completing registration, an verification email is sent. We should also implement the forgot password process as welll.

Passwords should be encrypted using `jbcrypt`.

There will also be a default `groups` table. This table will persist permissions.

**Comment by edadma** [comment]
now that TIMESTAMP and ARRAY are implemented (for H2 anyway, our dev database) we can start on this issue next.

**Comment by emaxedon** [comment]
Hey, I noticed I was able to register with empty strings for email and password. No biggy - but I think these should not be allowed to be empty or null.

**Comment by edadma** [comment]
fixed

**Comment by edadma** [comment]
Bearer authentication scheme: https://tools.ietf.org/html/rfc6750

**Comment by emaxedon** [comment]
Noticed that when registering at `/auth/register`, the user's `createdTime` is `null`. Also, the `password` is still being return in the response, and shouldn't be.

```
"id": 2,
"email": "edward@vinctus.com",
"createdTime": null,
"updatedTime": null,
"state": null,
"groups": [
  "user"
],
"password": "$2a$10$AW3NAVjutB72ChEaq50ybOQ.W1ujq1Hc8MprnEz5.0a2SUdrFETnm"
```

Good job otherwise! Really neat.

**Comment by edadma** [comment]
fixed createdTime = null problem
register only returns token

**Comment by edadma** [comment]
try this in SBT/command line:

SBT: ~re-start examples/test

command line: curl -v -H "Content-Type: application/json" -X POST -d '{"email":"admin@example.com","password":"password"}' http://localhost:8080/auth/login

response:
{
  "data": "the_access_token"
}

command line: curl -v -X GET "http://localhost:8080/r" -H "Authorization: Bearer the_access_token"

response (access granted to a protected resource):
{
  "data": []
}

command line (without bearer token): curl -v -X GET "http://localhost:8080/r"

response (access denied): empty (401)

**Comment by edadma** [comment]
the "get /auth/logout" route now works as expected

**Comment by emaxedon** [comment]
And how would register work?

**Comment by emaxedon** [comment]
Not a biggy, was wondering if we can change "token" to "access_token" in the response. I think it's more commonly called that.

**Comment by emaxedon** [comment]
I also noticed the password is still being returned in the response json when getting user data. This shouldn't be the case.

**Comment by edadma** [comment]
this a separate issue that hasen't been created yet

it's the "secret" keyword which has'nt been gotten to yet

**Comment by edadma** [comment]
### Protected Resource

Here's a REPL snippet

```
> ~runMain xyz.hyperreal.energize.REPLMain
[info] Running xyz.hyperreal.energize.REPLMain 
Welcome to Energize version 0.6.
Type in expressions to have them evaluated.
Type help for more information.

conn0: url=jdbc:h2:mem: user=SA
H2 JDBC Driver 1.4.193 (2016-10-31)

> l examples/test

> get /users
(401,WrappedArray((realm,Protected)))

> post /auth/login {email: "admin@example.com", password: "password"}
(200,{
  "data": "fpedfkdrhdnydvw"
})

> v $bearer fpedfkdrhdnydvw

> get /users
(200,{
  "data": [
    {
      "id": 1,
      "email": "admin@example.com",
      "createdTime": "2017-02-08T17:58:16.617-05:00",
      "updatedTime": null,
      "state": null,
      "groups": [
        "admin",
        "user"
      ],
      "password": "$2a$10$ORwKOKIIIkl96ckITrK3T.jNSq7C.S9uiPftvQwJI94kzAGHTaJEW"
    }
  ]
})

> get /auth/logout
(204,null)

> get /users
(401,WrappedArray((realm,Protected)))

> q
```

This issue is now closed!
